# Generated by Django 3.2.5 on 2023-12-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('name', models.CharField(max_length=127)),
                ('salary', models.FloatField()),
                ('company', models.CharField(max_length=64)),
            ],
        ),
    ]
